last_update = 1688547956228
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "97790580fb27425381c720907dd2b50b2538243a8fe1849fa4ba96754f90d37e"

[[mappings]]
name = "Minecraft Bedrock"
proto = "udp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 49440

[[mappings]]
name = "Minecraft Java"
proto = "tcp"
tunnel_ip = "147.185.221.181"
tunnel_from_port = 30736
local_port = 25565
